language: scala

jdk: oraclejdk8

scala:
   - 2.12.4

script:
   - sbt clean test

notifications:
  email: false
  slack:
    secure: "pOmA2EvuTEsRUGGdIQ6RN5xlcbBzYzFMzX+UYtLR4pdBCEhH4FnM3ksMd1RM4+GPXvxgxIyql9dkuoPTU+G4rY/qJXCC9YAufrOG2yWu7AGCgX5pvuP2F6xpmJ5I6MKkiTUZsMsFcGc5OZgsDL5nt6QysRsQhhlm0lB5c3SdxaJBjqNQwxGLCFgp0ZqPDDZP4OlAFL9LZ/muciacVj/RSBAO/CWryeStHwYA+1FfjuRN9iYiVbN3SHSz+KNuX6siWD3GL808Hjg4mjZCyk4ns6ZtxsYh4eaN73JZKivb6sSnJdlDZSD8SHJXlch64VzRKh0vwzTsOfY76MYmOLLDmhIXJhd0YZh7ICto5KnUpOpYh/6g/5nQXt3XbeuGmMYgJMnyaTYeG4L2bCFM1VRYSWm/wEQcIeb8HZ4iaTkWB3uHXlSgXaVwMHT9hphI1XzQKrEA+tmKwNdk2XhKXfG5cNgGlAbX71+AnLIZAQw9F47xXbRP0DVd7loAIIhwj1U6LOHENx0/ffJT/AiBq6AIULcLbDBDjDj/n9Dbm5GZYmpNVhaSx/+ue6bsa8LBrFxxYL1dQ4xoTyr9FkLRulS23yQ+x9DF60JxUgPj9jdVAlyUyGp86JQQkn9rwKdHAUkVvdMORrA8EqePivzMiT3cvgNwcirY28STzPnpMBbWlbE="
